= Micrometer CloudWatch
Tommy Ludwig <tludwig@vmware.com>
:toc:
:sectnums:
:system: cloudwatch2

Amazon CloudWatch is a dimensional time-series SaaS on Amazon's cloud.

include::install.adoc[]

NOTE: A deprecated module `micrometer-registry-cloudwatch` also exists with compatibility for AWS SDK v1. However, the non-deprecated `micrometer-registry-cloudwatch2` module for AWS SDK v2 should be preferred.

== Configuring

[source,java]
----
CloudWatchConfig cloudWatchConfig = new CloudWatchConfig() {
    @Override
    public String get(String s) {
        return null;
    }

    @Override
    public String namespace() {
        return "mynamespace";
    }
};
MeterRegistry meterRegistry = new CloudWatchMeterRegistry(cloudWatchConfig, Clock.SYSTEM, CloudWatchAsyncClient.create());
----

You can provide your own `CloudWatchAsyncClient` to the constructor of the registry.

`CloudWatchConfig` is an interface with a set of default methods. If, in the implementation of `get(String k)`, rather than returning `null`, you instead bind it to a property source, you can override the default configuration. For example, Micrometer support in https://spring.io/projects/spring-cloud-aws:[Spring Cloud AWS] binds properties prefixed with `management.metrics.export.cloudwatch` directly to the `CloudWatchConfig`:

[source,yml]
----
management.metrics.export.cloudwatch:
    namespace: YOURNAMESPACE

    # You will probably want disable publishing in a local development profile.
    enabled: true

    # The interval at which metrics are sent to CloudWatch. The default is 1 minute.
    step: 1m
----
